#!/bin/sh

awk 'NR==1 { print "**" $0 "**" } NR!=1 { print $0 }' $1 | \
sed \
  -e 's/\] [0-9][0-9]-/] /g' \
  -e 's#^\[PASS\]#![PASS](http://placehold.it/10/00cc00/000000?text=+)#g' \
  -e 's#^\[SKIP\]#![SKIP](http://placehold.it/10/cccc00/000000?text=+)#g' \
  -e 's#^\[FAIL\]#![FAIL](http://placehold.it/10/cc0000/000000?text=+)#g' | \
awk '(NR==1){print $0} (NR>1){printf $0 "&ensp;&ensp;"}'
