#!/bin/bash

SCRIPTDIR="$(readlink -f $(dirname $(type -p $0)))"
LOGDIR="${LOGDIR:-$SCRIPTDIR/logs}"

function wrapper {

	echo -e "\n% make-clean-script"
	$SCRIPTDIR/make-clean-script || exit $?

}

mkdir -p $LOGDIR
wrapper &> "$LOGDIR/make-clean.log"
