#!/bin/bash

SCRIPTDIR="$(readlink -f $(dirname $(type -p $0)))"

URL=$1
BRANCH=$2
LOGDIR=$3

TMPDIR=$(mktemp -d)
git clone -b $BRANCH $URL $TMPDIR &> /dev/null

status=0
for t in $SCRIPTDIR/[0-9][0-9]-*; do

	shortname=$(basename $t)

	[[ ! -x $t ]] && echo "[SKIP] $shortname" && continue

	cp -r $TMPDIR $TMPDIR.$shortname

	( cd $TMPDIR.$shortname && LOGDIR=$LOGDIR eval $t &> /dev/null )
	if [[ $? -ne 0 ]] ; then
		echo "[FAIL] $shortname"
		status=1
	else
	        echo "[PASS] $shortname"
	fi
	rm -rf $TMPDIR.shortname

done

rm -rf $TMPDIR
exit $status
